name: "不具合報告"
description: "不具合を報告する"
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます!
        以下の点にご注意ください:
        - 描画に関するバグはOptifineやSodiumなどの軽量化modが原因の可能性があります。必ずバニラ環境で確認してから不具合報告を行ってください。
  - type: textarea
    attributes:
      label: 詳細
      description: 不具合についてできるだけ詳しく説明してください。
      placeholder: |
        例: `tag:__`を実行した際に、想定していた動作は〇〇だが、実際は△△になる。
    validations:
      required: true
  - type: markdown
    attributes:
      value: 以下はオプションです。記入していただくとバグの解決がよりスムーズになります。
  - type: textarea
    attributes:
      label: 再現手順
      description: 報告する不具合の再現手順を記入してください。
      placeholder: |
        例:
        1. functionを実行する
        2. 不具合の発生
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 環境
      description: 不具合が発生した環境をお選びください。
      options:
        - label: シングルプレイ(LANで公開も含む)
        - label: マルチプレイ
  - type: textarea
    attributes:
      label: 環境の詳細
      description: 不具合が発生した環境を詳しく記入してください。
      placeholder: |
        例:
        paper-1.20.1-170、Geyser-Spigot導入済み
  - type: textarea
    attributes:
      label: その他
      description: その他になにかあれば記入してください。
